# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: localhost
ansible_connection: local
ansible_user: vagrant

# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: virtual
host_name: vagrant-wrapper
host_region: local
host_site: dev
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"
host_description: "Local Vagrant development VM"
