# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: server-64gb-storage
host_description: "Central storage device"
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 192.168.1.116
host_primary_interface: "enp3s0"
host_ipv4_subnet: 24

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "{{ host_ipv4 }}" # How to access the host
ansible_user: "{{ vault_server_username }}" # Account to connect as
ansible_become_password: "{{ vault_password }}" # Account password (for sudo)

# -------------------------------------------------------------------
# UBUNTUPRO
# -------------------------------------------------------------------
ubuntupro_attach: true

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------
zfs:
  fastpool:
    pool_properties: {}
    vdevs:
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_CT1000BX500SSD1_2216E629AC18
          - /dev/disk/by-id/scsi-SATA_SanDisk_SDSSDH3_22087N455301
    datasets:
      compositions:
        policy: critical
        snapshots_discover_children: true
        datasets:
          splitwise:
            policy: critical
      pools:
        datasets:
          vms:
            policy: critical
            datasets:
              vm-claude-dev:
                policy: critical
              vm-homeassistant:
                policy: critical
              vm-downloads:
                policy: critical
              vm-media:
                policy: critical
  slowpool:
    vdevs:
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_ST16000NT001-3LV_ZR61CRHS
          - /dev/disk/by-id/scsi-SATA_WDC_WD40EFZX-68A_WD-WX12DA08KR45
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_WDC_WD40EFZX-68A_WD-WX12DA0R1V78
          - /dev/disk/by-id/scsi-SATA_WDC_WD40EFZX-68A_WD-WX82DA1RHH08
      - type: mirror
        disks:
          - /dev/disk/by-id/scsi-SATA_ST4000VN008-2DR1_ZDHB6E35
          - /dev/disk/by-id/scsi-SATA_ST4000VN008-2DR1_ZDHB880S
      - type: mirror
        disks:
          - "/dev/disk/by-id/{{ vault_ironwolfpro_16tb_alpha }}"
          - "/dev/disk/by-id/{{ vault_ironwolfpro_16tb_beta }}"
    datasets:
      shared:
        datasets:
          models:
            policy: high
          photos:
            policy: critical
          syncthing:
          logs:
            datasets:
              loki:
                policy: high
                extra_zfs_properties:
                  compression: lz4
                  recordsize: 128K
          metrics:
            datasets:
              zfs:
                policy: high
          media:
            datasets:
              shows:
                policy: low
              movies:
                policy: low
              music:
                policy: critical
              books:
                policy: critical
              audiobooks:
                policy: critical
              downloads:
                datasets:
                  torrents:
              podcasts:
                policy: critical
              youtube:
      charlie:
        policy: none
        datasets:
          syncthing:
            policy: critical
          photos:
            policy: critical
          email:
            policy: critical

# -------------------------------------------------------------------
# MISC
# -------------------------------------------------------------------
# Media storage
shared_media_path: /slowpool/shared/media

# -------------------------------------------------------------------
# NFS
# -------------------------------------------------------------------
zfs_nfs_exports:
  - dataset: slowpool/shared/media
    options: "rw=100.64.0.0/10:192.168.1.0/24:192.168.122.0/24,anonuid=1000,anongid=1000,no_root_squash,all_squash"
  - dataset: slowpool/charlie/photos
    options: "rw=100.64.0.0/10:192.168.1.0/24:192.168.122.0/24,anonuid=1000,anongid=1000,no_root_squash,all_squash"
  - dataset: slowpool/shared/models
    options: "rw=100.64.0.0/10:192.168.1.0/24:192.168.122.0/24,anonuid=1000,anongid=1000,no_root_squash,all_squash"

# -------------------------------------------------------------------
# CNAMES
# These cnames will be aliased to this machine's FQDN.
# -------------------------------------------------------------------
cnames:
  - jellyfin.{{ domainname_infra }}
  - lidarr.{{ domainname_infra }}
  - karakeep.{{ domainname_infra }}
  - prowlarr.{{ domainname_infra }}
  - sonarr.{{ domainname_infra }}
  - radarr.{{ domainname_infra }}
  - immich.{{ domainname_infra }}
  - gitea.{{ domainname_infra }}
  - musicassistant.{{ domainname_infra }}
  - traefik.{{ host_fqdn }}
  - syncthing.{{ domainname_infra }}
  - freshrss.{{ domainname_infra }}
  - tubesync.{{ domainname_infra }}
  - audiobookshelf.{{ domainname_infra }}
  - libation.{{ domainname_infra }}
  - librofm.{{ domainname_infra }}
  - home.{{ domainname_infra }}
  - wallabag.{{ domainname_infra }}
  - jellyseerr.{{ domainname_infra }}
  - translate.{{ domainname_infra }}
  - loki.{{ domainname_infra }}
  - chat.{{ domainname_infra }}
