- name: Out on the internet server
  hosts: hetzner-sites
  roles:
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: start
      tags: [monitoring]
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]
    - role: virtual-hetzner
      tags: [virtual]
    - role: user-site-deployment
    - role: system-zfs
      tags: [system, zfs]
    - role: system-zfs-policy
      tags: [system, zfs]
    - role: client-nfs
      tags: [client]
    - role: composition-reverseproxy
      tags: [compositions]
    - role: composition-container-management
      tags: [compositions]
    - role: composition-awfulwoman
      tags: [compositions]
    - role: composition-zfs-api
      tags: [compositions, zfs]
    - role: system-promtail
      tags: [system, promtail]
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: success
      tags: [monitoring]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
