---
system_homebrew_bin: >-
  {{
    '/home/linuxbrew/.linuxbrew/bin/brew' if ansible_facts['system'] == 'Linux'
    else ('/opt/homebrew/bin/brew' if ansible_facts['architecture'] == 'arm64' else '/usr/local/bin/brew')
  }}
