---
- name: Deploy Promtail to all Docker hosts
  hosts:
    - generic-64gb-storage
    - homebrain
    - deedee
    - generic-8gb-backups
    - albion
    - belinda
    - sites

  roles:
    - role: system-promtail
