---
- name: Deploy Promtail to all Docker hosts
  hosts:
    - server-64gb-storage
    - minipc-8gb-homebrain
    - raspberry-pi4-2gb-deedee
    - server-8gb-backups
    - raspberry-pi4-4gb-albion
    - raspberry-pi5-4gb-belinda
    - vps-hetzner-public01

  roles:
    - role: system-promtail
