---
- name: NAS and general workloads
  hosts: server-64gb-storage
  roles:
  - role: monitoring-healthchecksio
    monitoring_healthchecksio_ping_type: start
    tags: [monitoring, monitoring-healthchecksio]
  - role: bootstrap-ubuntu-server
    tags: [bootstrap, bootstrap-ubuntu-server]
  - role: network-netplan
    tags: [network, network-netplan]
  - role: hardware-host-bus-adapter
    tags: [hardware, hardware-host-bus-adapter]
  - role: system-wakeonlan
    tags: [system, system-wakeonlan]
  - role: client-nut
    tags: [client, client-nut]
  - role: system-zfs
    tags: [system, zfs, system-zfs]
  - role: system-zfs-policy
    tags: [system, zfs, system-zfs-policy]
  - role: system-mqtt2cmd
    tags: [system, system-mqtt2cmd]
  - role: infothrill.nullmailer
    become: true
  - role: server-nfs
    tags: [server, server-nfs]
  - role: virtual-qemu-host
    tags: [virtual, virtual-qemu-host]
  - role: backups-zfs-client
    tags: [backups, zfs, backups-zfs-client]
  - role: composition-zfs-api
    tags: [composition, zfs, composition-zfs-api]
  - role: composition-victoriametrics
    tags: [composition, composition-victoriametrics]
  - role: composition-loki
    tags: [composition, loki, composition-loki]
  - role: composition-reverseproxy
    tags: [composition, composition-reverseproxy]
  - role: composition-container-management
    tags: [composition, composition-container-management]
  - role: composition-github2karakeep
    tags: [composition, composition-github2karakeep]
  - role: composition-finances
    tags: [composition, composition-finances]
  - role: composition-gitea
    tags: [composition, composition-gitea]
  - role: composition-gitea-runners
    tags: [composition, composition-gitea-runners]
  - role: composition-jellyfin
    tags: [composition, composition-jellyfin]
  - role: composition-immich
    tags: [composition, composition-immich]
  - role: composition-llm-inference-calculator
    tags: [composition, composition-llm-inference-calculator]
  - role: composition-audiobookshelf
    tags: [composition, composition-audiobookshelf]
  - role: composition-downloads
    tags: [composition, composition-downloads]
  - role: composition-syncthing
    tags: [composition, composition-syncthing]
  - role: composition-karakeep
    tags: [composition, composition-karakeep]
  - role: composition-freshrss
    tags: [composition, composition-freshrss]
  - role: composition-tubesync
    tags: [composition, composition-tubesync]
  - role: composition-homepage
    tags: [composition, composition-homepage]
  - role: composition-piper
    tags: [composition, composition-piper]
  - role: composition-gotosocial
    tags: [composition, composition-gotosocial]
  - role: composition-libretranslate
    tags: [composition, composition-libretranslate]
  - role: composition-n8n
    tags: [composition, composition-n8n]
  - role: composition-memorybank
    tags: [composition, composition-memorybank]
  - role: composition-paperless-ngx
    tags: [composition, composition-paperless-ngx]
  - role: composition-mcp-kagisearch
    tags: [composition, composition-mcp-kagisearch]
  - role: system-emailbackup
    tags: [system, system-emailbackup]
  - role: system-smartmontools
    tags: [system, system-smartmontools]
  - role: system-promtail
    tags: [system, system-promtail]
    # - role: system-sleepuntil
    #   become: true
    # - role: system-powertop
  - role: monitoring-healthchecksio
    monitoring_healthchecksio_ping_type: success
    tags: [monitoring, monitoring-healthchecksio]

  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
