- name: Storage NAS - ZFS API
  hosts: server-64gb-storage
  roles:
  - role: composition-zfs-api
    tags: [composition, zfs, composition-zfs-api]

  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
