---
- name: Install Ansible (macOS)
  ansible.builtin.include_tasks: install-macos.yaml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Ansible (Ubuntu/Debian)
  ansible.builtin.include_tasks: install-ubuntu.yaml
  when: ansible_facts['os_family'] == 'Debian'
