- name: Configure a host to pull ZFS backups from clients
  hosts: zfs_backup_servers
  roles:
  - role: system-zfs
    tags: [system, zfs, system-zfs]
  - role: system-zfs-policy
    tags: [system, zfs, system-zfs-policy]
  - role: backups-zfs-server
    tags: [backups, zfs, backups-zfs-server]
  - role: composition-container-management
    tags: [composition, composition-container-management]
  - role: composition-reverseproxy
    tags: [composition, composition-reverseproxy]
  - role: composition-zfs-api
    tags: [composition, zfs, composition-zfs-api]

  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
