- name: Restart Traefik
  ansible.builtin.command:
    cmd: docker restart traefik
  register: _restart_traefik
  failed_when:
    - _restart_traefik.rc != 0
    - "'No such container' not in _restart_traefik.stderr"
  changed_when: _restart_traefik.rc == 0
