# code: language=ansible
composition_name: openzim-mcp

composition_openzim_mcp_version: "latest"
composition_openzim_mcp_zim_path: "/slowpool/shared/zim"
composition_openzim_mcp_zim_download_path: "{{ composition_openzim_mcp_zim_path }}/library"
composition_openzim_mcp_container_zim_path: "/data/library"

composition_openzim_mcp_subdomains:
  - zim

composition_openzim_mcp_auth_token: "{{ vault_openzim_mcp_auth_token }}"

composition_openzim_mcp_zim_files:
  - url: "https://lb.download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2026-02.zim"
    dest: "wikipedia_en_all_maxi_2026-02.zim"
