# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: unmanaged
host_name: laptop-macbook-air-m4-16gb-work-FXHP0C5935
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domain_name }}"
host_description: Charlie's work laptop

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
host_ipv4: false
host_mac: false
