# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: unmanaged
host_name: printer-epson-xp610
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domain_name }}"
host_description: A little inkjet printer that somehow still finds usage

# -------------------------------------------------------------------
# NETWORK
# -------------------------------------------------------------------
host_ipv4: false
host_mac: false
