- name: Testbed for dual-NIC Linux router setup
  hosts: mini-pc-test-router
  roles:
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: start
      tags: [monitoring]
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]
    - role: network-netplan
      tags: [network]
    - role: infothrill.nullmailer
      become: true
    - role: system-sshkey
      tags: [system]
    # - role: system-zfs
    # - role: infra-public-resources
    # - role: infra-named
    # - role: infra-certbot
    # - role: compositions
    # - role: backups-zfs-client
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: success
      tags: [monitoring]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
