- name: RANDOLPH!
  hosts: raspberry-pi4-4gb-randolph
  roles:
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: start
      tags: [monitoring]
    - role: hardware-raspberry-pi
      tags: [hardware]
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]
    - role: network-netplan
      tags: [network]
    - role: infothrill.nullmailer
      become: true
    - role: system-sshkey
      tags: [system]
    - role: system-zfs
      tags: [system, zfs, system-zfs]
    - role: system-zfs-policy
      tags: [system, zfs, system-zfs-policy]
