all:
  # -------------------------------------------------------------------
  # UNASSIGNED HOSTS
  # Only hosts not assigned to any group should need to be lsited here
  # -------------------------------------------------------------------
  # hosts:

  children:

    # -------------------------------------------------------------------
    # MANAGED INFRA
    # Everything that is managed by Ansible is listed here
    # -------------------------------------------------------------------
    infra:
      hosts:
        # albion:
        generic-8gb-backups:
        mini-pc-8gb-homebrain:
        mac-mini-m4-16gb-malcolm:
        raspberry-pi4-2gb-pikvm:
        hetzner-sites:
        generic-64gb-storage:
        mini-pc-test-router:
        raspberry-pi4-2gb-deedee:
        raspberry-pi4-4gb-randolph:
        raspberry-pi4-8gb-randy:
        raspberry-pi5-4gb-belinda:


    # -------------------------------------------------------------------
    # UBUNTU SERVERS
    # All servers that run Ubuntu
    # -------------------------------------------------------------------
    ubuntu_servers:
      hosts:
        # albion:
        generic-8gb-backups:
        mini-pc-8gb-homebrain:
        hetzner-sites:
        generic-64gb-storage:
        mini-pc-test-router:
        raspberry-pi4-2gb-deedee:
        raspberry-pi4-4gb-randolph:
        raspberry-pi4-8gb-randy:
        raspberry-pi5-4gb-belinda:

    # -------------------------------------------------------------------
    # MACOS SERVERS
    # All servers that run MacOS
    # -------------------------------------------------------------------
    macos_servers:
      hosts:
        mac-mini-m4-16gb-malcolm:

    # -------------------------------------------------------------------
    # RASPBERRY PI
    # All Raspberry Pi hosts, regardless of role or OS
    # -------------------------------------------------------------------
    raspberry_pi:
      hosts:
        # albion:
        raspberry-pi4-2gb-pikvm:
        raspberry-pi4-2gb-deedee:
        raspberry-pi4-4gb-randolph:
        raspberry-pi4-8gb-randy:
        raspberry-pi5-4gb-belinda:


    # -------------------------------------------------------------------
    # HOME AUTOMATION
    # Hosts running home automation services
    # -------------------------------------------------------------------
    homeautomation:
      hosts:
        mini-pc-8gb-homebrain:

    # -------------------------------------------------------------------
    # ZFS
    # Hosts that use ZFS
    # -------------------------------------------------------------------
    zfs:
      hosts:
        generic-64gb-storage:
        mini-pc-8gb-homebrain:
        generic-8gb-backups:
        # albion: # Has died
        hetzner-sites:
        raspberry-pi5-4gb-belinda:
        raspberry-pi4-2gb-deedee:
        # raspberry-pi4-4gb-randolph:
        # raspberry-pi4-8gb-randy:

    # -------------------------------------------------------------------
    # ZFS REPLICATION SOURCES
    # Hosts acting as replication sources
    # -------------------------------------------------------------------
    zfs_backup_clients:
      hosts:
        generic-64gb-storage:
        mini-pc-8gb-homebrain:
        hetzner-sites:
        raspberry-pi4-2gb-deedee:
        # raspberry-pi4-4gb-randolph:
        # raspberry-pi4-8gb-randy:

    # -------------------------------------------------------------------
    # ZFS REPLICATION DESTINATIONS
    # Hosts acting as replication destination
    # -------------------------------------------------------------------
    zfs_backup_servers:
      hosts:
        generic-8gb-backups:
        raspberry-pi5-4gb-belinda:

    # -------------------------------------------------------------------
    # ZFS REPLICATION DESTINATIONS - OFFSITE
    # Hosts acting as offsite replication destination
    # NOTE: the only offsite host died - needs replacing
    # -------------------------------------------------------------------
    # zfs-backup-offsite:
    #   hosts:
    #     albion:

    # -------------------------------------------------------------------
    # PUBLIC SERVERS
    # Hosts that static sites can be deployed to
    # -------------------------------------------------------------------
    sitedeployment:
      hosts:
        hetzner-sites:

    # -------------------------------------------------------------------
    # VAGRANT HOSTS
    # Vagrant hosts, commonly used for development
    # -------------------------------------------------------------------
    vagrant:
      hosts:
        vagrant-wrapper:

    # Unmanaged devices are defined in hosts-unmanaged.yaml
