all:
  # -------------------------------------------------------------------
  # UNASSIGNED HOSTS
  # Only hosts not assigned to any group should need to be lsited here
  # -------------------------------------------------------------------
  # hosts:

  children:

    # -------------------------------------------------------------------
    # MANAGED INFRA
    # Everything that is managed by Ansible is listed here
    # -------------------------------------------------------------------
    infra:
      hosts:
        # host-albion:
        host-backups:
        host-homebrain:
        host-malcolm:
        host-pikvm:
        host-sites:
        host-storage:
        host-test-router:
        host-raspberry-pi4-2gb-roger:
        host-raspberry-pi4-4gb-rudolph:
        host-raspberry-pi4-8gb-randy:
        host-raspberry-pi5-4gb-belinda:


    # -------------------------------------------------------------------
    # UBUNTU SERVERS
    # All servers that run Ubuntu
    # -------------------------------------------------------------------
    ubuntu_servers:
      hosts:
        # host-albion:
        host-backups:
        host-homebrain:
        host-sites:
        host-storage:
        host-test-router:
        host-raspberry-pi4-2gb-roger:
        host-raspberry-pi4-4gb-rudolph:
        host-raspberry-pi4-8gb-randy:
        host-raspberry-pi5-4gb-belinda:

    # -------------------------------------------------------------------
    # MACOS SERVERS
    # All servers that run MacOS
    # -------------------------------------------------------------------
    macos_servers:
      hosts:
        host-malcolm:

    # -------------------------------------------------------------------
    # HOME AUTOMATION
    # Hosts running home automation services
    # -------------------------------------------------------------------
    homeautomation:
      hosts:
        host-homebrain:

    # -------------------------------------------------------------------
    # ZFS
    # Hosts that use ZFS
    # -------------------------------------------------------------------
    zfs:
      hosts:
        host-storage:
        host-homebrain:
        host-backups:
        # host-albion: # Has died
        host-sites:
        host-raspberry-pi5-4gb-belinda:
        host-raspberry-pi4-2gb-roger:
        # host-raspberry-pi4-4gb-rudolph:
        # host-raspberry-pi4-8gb-randy:

    # -------------------------------------------------------------------
    # ZFS REPLICATION SOURCES
    # Hosts acting as replication sources
    # -------------------------------------------------------------------
    zfs_backup_clients:
      hosts:
        host-storage:
        host-homebrain:
        host-sites:
        host-raspberry-pi4-2gb-roger:
        # host-raspberry-pi4-4gb-rudolph:
        # host-raspberry-pi4-8gb-randy:

    # -------------------------------------------------------------------
    # ZFS REPLICATION DESTINATIONS
    # Hosts acting as replication destination
    # -------------------------------------------------------------------
    zfs_backup_servers:
      hosts:
        host-backups:
        host-raspberry-pi5-4gb-belinda:

    # -------------------------------------------------------------------
    # ZFS REPLICATION DESTINATIONS - OFFSITE
    # Hosts acting as offsite replication destination
    # NOTE: the only offsite host died - needs replacing
    # -------------------------------------------------------------------
    # zfs-backup-offsite:
    #   hosts:
    #     host-albion:

    # -------------------------------------------------------------------
    # PUBLIC SERVERS
    # Hosts that static sites can be deployed to
    # -------------------------------------------------------------------
    sitedeployment:
      hosts:
        host-sites:

    # -------------------------------------------------------------------
    # VAGRANT HOSTS
    # Vagrant hosts, commonly used for development
    # -------------------------------------------------------------------
    vagrant:
      hosts:
        vagrant-wrapper:

    # Unmanaged devices are defined in hosts-unmanaged.yaml
