# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: raspberry-pi5-4gb-belinda
host_name_medium: pi-belinda
host_name_short: belinda
host_region: ber
host_site: kberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"
host_description: "Raspberry Pi 5, decommissioned as backup server (infra#300), awaiting new role"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 192.168.1.117
host_primary_interface: "eth0"
host_ipv4_subnet: 24
host_tailscale_ipv4: 100.80.1.117
tailscale_exit_node: false

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "{{ host_ipv4 }}" # TODO: Replace this with `host_fqdn` once DNS infra is up and running
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# UBUNTUPRO
# -------------------------------------------------------------------
ubuntupro_attach: false

# -------------------------------------------------------------------
# BOOTSTRAP
# -------------------------------------------------------------------
bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_hide_undervoltage_warnings: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt
raspberry_pi_config_overrides:
  - "dtoverlay=cooling_fan"
  - "dtparam=pciex1"
  - "dtparam=pciex1_gen=3" # https://docs.radxa.com/en/accessories/storage/penta-sata-hat/penta-for-rpi5
  - "dtoverlay=pcie-32bit-dma-pi5" # JMB585 AHCI probe fails (errno=-12) since a kernel regression forces 32bit DMA: https://github.com/raspberrypi/linux/issues/7375
