- name: ZFS Backup Clients
  import_playbook: ../zfs_backup_clients/core.yaml
- name: ZFS Offsite Servers
  import_playbook: ../zfs_backup_offsite/core.yaml
- name: ZFS Backup Servers
  import_playbook: ../zfs_backup_servers/core.yaml
