#!/bin/bash
set -euo pipefail

# Script to fetch SSH public keys from GitHub and update authorized_keys
# Generated by Ansible - DO NOT EDIT MANUALLY

GITHUB_USER="{{ automation_key_updater_username }}"
TARGET_USER="{{ automation_key_updater_target_user }}"
COMMENT="github.com/${GITHUB_USER}"
MARKER_START="# BEGIN GITHUB KEYS: ${GITHUB_USER}"
MARKER_END="# END GITHUB KEYS: ${GITHUB_USER}"

# Get target user's home directory
TARGET_HOME=$(eval echo ~${TARGET_USER})
AUTHORIZED_KEYS="${TARGET_HOME}/.ssh/authorized_keys"

# Ensure .ssh directory exists
mkdir -p "${TARGET_HOME}/.ssh"
chmod 700 "${TARGET_HOME}/.ssh"

# Fetch keys from GitHub
GITHUB_KEYS=$(curl -fsSL "https://github.com/${GITHUB_USER}.keys" || {
    echo "Failed to fetch keys from GitHub" >&2
    exit 1
})

# Ensure authorized_keys exists
touch "${AUTHORIZED_KEYS}"
chmod 600 "${AUTHORIZED_KEYS}"

# Remove old GitHub keys section if it exists
sed -i.bak "/${MARKER_START}/,/${MARKER_END}/d" "${AUTHORIZED_KEYS}"

# Append new GitHub keys with markers
{
    echo "${MARKER_START}"
    echo "${GITHUB_KEYS}"
    echo "${MARKER_END}"
} >> "${AUTHORIZED_KEYS}"

# Set correct ownership
chown -R "${TARGET_USER}:${TARGET_USER}" "${TARGET_HOME}/.ssh"

echo "Successfully updated GitHub SSH keys for ${TARGET_USER}"
