# code: language=ansible

client_cert_distribution_source_host: router-4gb-bertha
client_cert_distribution_source_dir: /fastpool/acme/distribution
client_cert_distribution_bundle_name: "*.{{ domainname_infra }}"
client_cert_distribution_install_dir: /etc/ssl/internal-wildcard
client_cert_distribution_healthcheck: true
client_cert_distribution_healthcheck_name: "{{ inventory_hostname }} - Internal Wildcard Cert"
