- name: Belinda the Backup Server
  hosts: host-raspberry-pi5-4gb-belinda
  roles:
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: start
      tags: [monitoring]
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]
    - role: network-netplan
      tags: [network]
    - role: hardware-raspberry-pi
      tags: [hardware]
    - role: system-zfs
      tags: [system, zfs]
    - role: system-zfs-policy
      tags: [system, zfs]
    - role: backups-zfs-server
      tags: [backups, zfs]
    - role: composition-container-management
      tags: [compositions]
    - role: composition-reverseproxy
      tags: [compositions]
    - role: composition-zfs-api
      tags: [compositions, zfs]
    - role: client-nut
      tags: [client]
    - role: infothrill.nullmailer
      become: true
    - role: system-promtail
      tags: [system, promtail]
    - role: monitoring-healthchecksio
      monitoring_healthchecksio_ping_type: success
      tags: [monitoring]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
