ubuntu_cloud_init_mount_path: /Volumes/cidata
ubuntu_cloud_init_hostname: ubuntu-server
ubuntu_cloud_init_timezone: Europe/Berlin
ubuntu_cloud_init_username: "{{ vault_server_username }}"
ubuntu_cloud_init_groups:
  - users
  - adm
  - sudo
ubuntu_cloud_init_github_username: awfulwoman
ubuntu_cloud_init_ssh_pwauth: false
ubuntu_cloud_init_package_update: false
ubuntu_cloud_init_package_upgrade: false

# Static IP — leave ubuntu_cloud_init_ip unset for DHCP
ubuntu_cloud_init_ip: ""
ubuntu_cloud_init_prefix: 24
ubuntu_cloud_init_gateway: ""
ubuntu_cloud_init_interface: eth0
ubuntu_cloud_init_dns:
  - 192.168.1.1
