# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: samson
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domain_name }}"
host_description: "Used as a jumphost and for running Claude Code"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 192.168.1.112
host_ipv4_subnet: 24
host_primary_interface: "eth0"
tailscale_exit_node: true

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "{{ host_ipv4 }}"
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# UBUNTUPRO
# -------------------------------------------------------------------

ubuntupro_attach: false

# -------------------------------------------------------------------
# BOOTSTRAP
# -------------------------------------------------------------------#
bootstrap_ubuntu_timezone: "Europe/Berlin"

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt

# -------------------------------------------------------------------
# REPOS
# -------------------------------------------------------------------
repos:
  - repo: awfulwoman/infra
    name: infra
  - repo: awfulwoman/obsidian
    name: obsidian

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    vdevs:
      - type: stripe
        disks: /dev/disk/by-id/usb-USB_SanDisk_3.2Gen1_0501f56e8b204d273e4fefdd60408eefbbb1a99d524666fc3243c7d31f73791ef10200000000000000000000708c093200920b10915581071f2f4514-0:0
    datasets:
      compositions:
