# Composition name (used by composition-common dependency)
composition_name: vikunja

composition_vikunja_subdomains:
  - vikunja

vikunja_db_password: "{{ vault_vikunja_db_password }}"
vikunja_secret_key: "{{ vault_vikunja_secret_key }}"
