# code: language=ansible

- name: Ensure composition is enabled
  ansible.builtin.assert:
    that:
      - composition_zfs_api_enabled
    fail_msg: "composition-zfs-api is not enabled"
    quiet: true

- name: Ensure ZFS is configured on host
  ansible.builtin.assert:
    that:
      - zfs is defined
    fail_msg: "ZFS must be configured (zfs variable) to use this composition"
    quiet: true

# ----------------------------
# Core tasks
# ----------------------------

- name: "Create compose file"
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ composition_root }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0774"

- name: "Create .env file"
  ansible.builtin.template:
    src: environment_vars.j2
    dest: "{{ composition_root }}/.environment_vars"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0774"

# ----------------------------
# Specific tasks
# ----------------------------

- name: Create app directory
  become: true
  ansible.builtin.file:
    path: "{{ composition_config }}/app"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0774"

- name: "Create Swagger API documentation"
  become: true
  ansible.builtin.template:
    src: swagger.yaml.j2
    dest: "{{ composition_config }}/app/swagger.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0774"

- name: Run Configure DNS role
  ansible.builtin.include_role:
    name: "network-register-subdomain"
  vars:
    configure_dns_subdomains: "{{ composition_zfs_api_subdomains }}"

# ----------------------------
# Start composition
# ----------------------------

- name: Start Docker Compose project
  community.docker.docker_compose_v2:
    project_src: "{{ composition_root }}"
    state: present
    remove_orphans: true
  notify: Restart Traefik
