- name: UK Server
  hosts: raspberry-pi4-4gb-albion
  roles:
  - role: monitoring-healthchecksio
    monitoring_healthchecksio_ping_type: start
    tags: [monitoring, monitoring-healthchecksio]
  - role: hardware-raspberry-pi
    tags: [hardware, hardware-raspberry-pi]
  - role: bootstrap-ubuntu-server
    tags: [bootstrap, bootstrap-ubuntu-server]
  - role: network-netplan
    tags: [network, network-netplan]
  - role: infothrill.nullmailer
    become: true
  - role: system-sshkey
    tags: [system, system-sshkey]
  - role: system-zfs
    tags: [system, zfs, system-zfs]
  - role: backups-zfs-archive-offsite
    tags: [backups, zfs, backups-zfs-archive-offsite]
  - role: network-ip-address-forwarding
    tags: [network, network-ip-address-forwarding]
  - role: client-nfs
    tags: [client, client-nfs]
  - role: composition-reverseproxy
    tags: [composition, composition-reverseproxy]
  - role: composition-container-management
    tags: [composition, composition-container-management]
  - role: composition-zfs-api
    tags: [composition, zfs, composition-zfs-api]
  - role: system-promtail
    tags: [system, promtail, system-promtail]
  - role: monitoring-healthchecksio
    monitoring_healthchecksio_ping_type: success
    tags: [monitoring, monitoring-healthchecksio]

  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
