---
- name: Dev stuff
  hosts: minipc-8gb-homebrain
  vars:
    compositions:
    - container-management
  roles:
  - role: composition-mqtt   # must run before owntracks and zigbee2mqtt
    tags: [composition, composition-mqtt]
  - role: composition-reverseproxy
    tags: [composition, composition-reverseproxy]
  - role: composition-container-management
    tags: [composition, composition-container-management]
  - role: composition-homeassistant
    tags: [composition, composition-homeassistant]
  - role: composition-matter
    tags: [composition, composition-matter]
  - role: composition-owntracks
    tags: [composition, composition-owntracks]
  - role: composition-zigbee2mqtt
    tags: [composition, composition-zigbee2mqtt]
  - role: composition-watchyourlan
    tags: [composition, composition-watchyourlan]
  - role: composition-zfs-api
    tags: [composition, composition-zfs-api]
  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
