- name: ZFS and backup stuff
  hosts: raspberry-pi5-4gb-belinda
  roles:
  - role: system-zfs
    tags: [system, zfs, system-zfs]
  - role: system-zfs-policy
    tags: [system, zfs, system-zfs-policy]
  - role: backups-zfs-server
    tags: [backups, zfs, backups-zfs-server]
  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
