# nfs_mounts:
#   - remote_server: host-storage
#     remote_path: /slowpool/shared/media
#     local_path: /mnt/media
#   - remote_server: host-backups
#     remote_path: /fastpool/archive
#     local_path: /mnt/archive
#     mount_options: "defaults,_netdev,ro"  # optional per-mount override

nfsclient_mount_options: "defaults,_netdev,x-systemd.after=network-online.target"
nfsclient_mount_options_macos: "resvport,rw"
