# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: virtual
host_name: vps-hetzner-public01
host_region: hetzner
host_site: cloud
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"
host_description: "Hetzner cloud server for public services"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 188.245.37.81

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
# ansible_host: "{{ host_ipv4 }}"
ansible_host: awfulwoman.com
ansible_user: "{{ vault_server_username }}"


bootstrap_ubuntu_timezone: "Europe/Berlin"


# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    device:
    vdevs:
      - type: stripe
        disks:
          - /dev/disk/by-id/scsi-0HC_Volume_104390137
    datasets:
      compositions:
        policy: critical
      sites:
        datasets:
          awfulwoman:
            policy: critical
          pixelfed:
            policy: critical
          gotosocial:
            policy: critical

# -------------------------------------------------------------------
# SITES
# -------------------------------------------------------------------

traefik_providers:
  - gotosocial
