# Composition name (used by composition-common dependency)
composition_name: finances

composition_finances_subdomains:
  - firefly
  - firefly-importer

firefly_cron_token: null
firefly_db_password: null
firefly_app_key: null
