- name: Storage NAS - ZFS API
  hosts: host-generic-64gb-storage
  roles:
    - role: composition-zfs-api
      tags: [compositions, zfs]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
