- name: Run certbot role
  hosts: raspberry-pi4-2gb-deedee
  roles:
    - role: infra-dhcpd
    - role: infra-named

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
