- name: Update Terraform
  hosts: raspberry-pi4-2gb-deedee
  roles:
  - role: infra-public-resources
    tags: [infra, terraform-public, infra-public-resources]
  - role: infra-private-resources
    tags: [infra, terraform-private, infra-private-resources]

  handlers:
  - name: Reboot host
    become: true
    ansible.builtin.reboot:
