# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: malcolm
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domain_name }}"
host_description: "Mac Mini M4 16GB"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 192.168.1.150
host_primary_interface: "enp3s0"
host_ipv4_subnet: 24

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "{{ host_ipv4 }}"
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# OLLAMA
# -------------------------------------------------------------------
system_ollama_env:
  OLLAMA_HOST: "0.0.0.0:11434"
  OLLAMA_NO_CLOUD: 1
  OLLAMA_NUM_PARALLEL: 4
  OLLAMA_MAX_LOADED_MODELS: 1
  OLLAMA_ORIGINS: "*"
  OLLAMA_KEEP_ALIVE: -1
  OLLAMA_KV_CACHE_TYPE: q8_0

system_ollama_models:
  - gemma3:4b
  - gemma3:12b
  - qwen3:14b

# -------------------------------------------------------------------
# CLAUDE
# -------------------------------------------------------------------
system_claude_settings_group: "staff"
system_claude_profile_file: ".zshrc"


# -------------------------------------------------------------------
# REPOS
# -------------------------------------------------------------------
repos:
  - repo: awfulwoman/infra
  - repo: awfulwoman/chives
  - repo: awfulwoman/podderton
  - repo: awfulwoman/ralph
  - repo: awfulwoman/awfulclaw
  - repo: awfulwoman/memorybank
  - repo: awfulwoman/personal-site
repos_base_dir: "{{ ansible_facts.user_dir }}/Code"
