#!/bin/bash
# Terraform wrapper with pre-configured variables
# Generated by Ansible role: infra-private-resources

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Variables configured by Ansible
HYPERVISOR_URI="{{ infra_privateresources_hypervisor_ssh_uri }}"
BRIDGE_INTERFACE="{{ infra_privateresources_bridge_interface }}"

# Pass subcommand first, then variables, then any additional args
# Usage: ./tf plan, ./tf apply, etc.
if [ $# -eq 0 ]; then
  echo "Usage: $0 <terraform-command> [additional-args]"
  echo "Example: $0 plan"
  echo "Example: $0 apply -auto-approve"
  exit 1
fi

exec terraform "$1" \
  -var="hypervisor_uri=${HYPERVISOR_URI}" \
  -var="bridge_interface=${BRIDGE_INTERFACE}" \
  "${@:2}"
