# Managed by Ansible - roles/composition-esphome
wifi_ssid: "{{ vault_homenetwork_ssid_24ghz }}"
wifi_password: "{{ vault_homenetwork_password }}"
api_key: "{{ vault_esphome_api_key }}"
ota_password: "{{ vault_esphome_ota_password }}"
ap_password: "{{ vault_esphome_ap_password }}"
wifi_domain: "{{ composition_esphome_wifi_domain }}"
