# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: raspberry-pi4-4gb-randolph
host_name_medium: pi-randolph
host_name_short: randolph
host_region: ber
host_site: xberg
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"
host_description: "Runs infrastructure tasks"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_ipv4: 192.168.1.3
host_ipv4_subnet: 24
host_primary_interface: "eth0"
host_mac: "dc:a6:32:71:1a:37"

# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: "{{ host_ipv4 }}"
ansible_user: "{{ vault_server_username }}"

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_bluetooth: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt

# -------------------------------------------------------------------
# UBUNTUPRO
# -------------------------------------------------------------------
ubuntupro_attach: false

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    vdevs:
      - type: stripe
        disks: "/dev/disk/by-id/usb-USB_SanDisk_3.2Gen1_04019e9fe6c6a78c38433ef74ac7c349509bbebdf62487b32caa928ab040d565e70500000000000000000000aca7d3dcff9c801891558107a32b60e7-0:0"
    datasets:
      compositions:
        policy: critical
        children_inherit_policy: true
        snapshots_discover_children: true

# -------------------------------------------------------------------
# ZFS POLICY
# -------------------------------------------------------------------
system_zfs_policy_healthchecksio_enabled: true
system_zfs_policy_mqtt_enabled: true

# -------------------------------------------------------------------
# CNAMES
# -------------------------------------------------------------------
cnames:
  - connect.{{ domainname_infra }}
