---
- name: Ensure dependencies are installed
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - yt-dlp
      - bubblewrap
      - socat
      - libonig-dev
    state: present

- name: Add GitHub CLI repository key
  become: true
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
    state: present

- name: Add GitHub CLI repository
  become: true
  vars:
    _gh_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ _gh_arch }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github-cli
    state: present

- name: Install GitHub CLI
  become: true
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
