- name: Mount NFS shares (macOS)
  ansible.builtin.include_tasks: mount-macos.yaml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install packages and mount NFS shares (Ubuntu/Debian)
  ansible.builtin.include_tasks: mount-ubuntu.yaml
  when: ansible_facts['os_family'] == 'Debian'
