---
- name: Malcolm
  hosts: host-malcolm
  roles:
    - role: bootstrap-macos-server
    - role: hardware-apple
    - role: automation-key-updater
    - role: system-repos
    - role: system-ollama
    - role: system-claude
    - role: system-git
