mailer_from_address: "noreply@{{ vault_olddomain_wc }}"
mailer_to_address: "hosts@{{ vault_olddomain_wc }}"
mailer_smtp_server: "{{ vault_smtp_host }}"
mailer_smtp_user: "{{ vault_smtp_user }}"
mailer_smtp_password: "{{ vault_smtp_password }}"
mailer_domain: "{{ vault_personal_domain }}"
mailer_host: "{{ host_fqdn }}"
mailer_error_address: "errors@{{ vault_olddomain_wc }}"
