- name: Belinda the Backup Server
  hosts: host-belinda
  # gather_facts: false
  # pre_tasks:
  #   - name: Check connectivity
  #     ansible.builtin.wait_for_connection:
  #       timeout: 5
  #     register: connectivity
  #     ignore_unreachable: true
  #     ignore_errors: true
  #   - name: Skip play if host is unreachable
  #     ansible.builtin.meta: end_host
  #     when: connectivity.failed | default(false)
  #   - name: Gather host facts, continuing as normal
  #     ansible.builtin.setup:
  roles:
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]
    - role: network-netplan
      tags: [network]
    - role: hardware-raspberry-pi
      tags: [hardware]
    - role: system-zfs
      tags: [system, zfs]
    - role: system-zfs-policy
      tags: [system, zfs]
    - role: backups-zfs-server
      tags: [backups, zfs]
    - role: composition-container-management
      tags: [compositions]
    - role: composition-reverseproxy
      tags: [compositions]
    - role: composition-zfs-api
      tags: [compositions, zfs]
    - role: client-nut
      tags: [client]
    - role: infothrill.nullmailer
      become: true
    - role: monitoring-healthchecksio
      tags: [monitoring]
    - role: system-promtail
      tags: [system, promtail]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
