- name: Out on the internet server
  hosts: vps-hetzner-public01
  roles:
    - role: network-netplan
      tags: [network]
    - role: bootstrap-ubuntu-server
      tags: [bootstrap]

  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
