# code: language=ansible

# ----------------------------
# Specific tasks
# ----------------------------

- name: Clone/update oggcamp site repository
  ansible.builtin.git:
    repo: "{{ composition_oggcamp_repo_url }}"
    dest: "{{ composition_config }}/repo"
    update: true
    version: HEAD
  register: git_clone

- name: Build Hugo site
  ansible.builtin.command:
    argv:
      - docker
      - run
      - --rm
      - --volume
      - "{{ composition_config }}/repo:/src"
      - hugomods/hugo:latest
      - hugo
  when: git_clone.changed
  changed_when: true

# ----------------------------
# Core tasks
# ----------------------------

- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ composition_root }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0774"

# ----------------------------
# Networking
# ----------------------------

- name: Register oggcamp subdomain to public IP
  hetzner.hcloud.zone_rrset:
    api_token: "{{ vault_hetzner_api_key_rw }}"
    zone: "{{ domainname_personal }}"
    name: "{{ composition_oggcamp_subdomain }}"
    type: "A"
    records:
      - value: "{{ ansible_host }}"
    state: present

# ----------------------------
# Start composition
# ----------------------------

- name: Start Docker Compose project
  community.docker.docker_compose_v2:
    project_src: "{{ composition_root }}"
    state: present
    remove_orphans: true
  notify: Restart Traefik
