# Loads default set of integrations. DO. NOT. REMOVE.
default_config:

#############################################################################
# HTTP
#############################################################################
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - ::1
    - fe80::/64
    - fe00::/64
    - fd00::/64
