# -------------------------------------------------------------------
# ANSIBLE
# -------------------------------------------------------------------
ansible_host: raspberry-pi4-4gb-albion.{{ vault_tailscale_tailnet_name }}
ansible_user: "{{ vault_server_username }}"
ansible_become_password: "{{ vault_password }}"

# -------------------------------------------------------------------
# IDENTITY
# -------------------------------------------------------------------
host_type: baremetal
host_name: raspberry-pi4-4gb-albion
host_name_medium: pi-albion
host_name_short: albion
host_region: ldn
host_site: camden
host_pfqdn: "{{ host_name }}.{{ host_site }}.{{ host_region }}"
host_fqdn: "{{ host_pfqdn }}.{{ domainname_infra }}"
host_description: "Remote node in London"

# -------------------------------------------------------------------
# NETWORK
# Hint: Use `network_netplan_config:` for more fine-grained control
# Docs: roles/network-netplan/README.md
# -------------------------------------------------------------------
host_primary_interface: "eth0"
tailscale_exit_node: true

# -------------------------------------------------------------------
# UBUNTUPRO
# -------------------------------------------------------------------

ubuntupro_attach: true

# -------------------------------------------------------------------
# BOOTSTRAP
# -------------------------------------------------------------------#
bootstrap_ubuntu_timezone: "Europe/London"

# -------------------------------------------------------------------
# HARDWARE
# -------------------------------------------------------------------
raspberry_pi_wifi: false
raspberry_pi_boot_config_location: /boot/firmware/config.txt
raspberry_pi_config_overrides:
  - "dtoverlay=gpio-fan,gpiopin=14,temp=60000"

# -------------------------------------------------------------------
# ZFS
# -------------------------------------------------------------------

zfs:
  fastpool:
    vdevs:
      - type: stripe
        disks: /dev/disk/by-id/scsi-SIntenso_SSD_SATAIII_512011020200
    datasets:
      # exampleset:
      #   infra:
      #     backup: true
      #   state: present
      #   delegation:
      #     users:
      #     permissions:
      #     local: true
      #     descendents:
      downloads:
      compositions:
      data:
        datasets:
          raw:
            properties:
              encryption: aes-256-gcm
              keylocation: "{{ vault_zfs_default_encryption_passphrase_path }}"
              keyformat: passphrase


# -------------------------------------------------------------------
# BACKUPS
# -------------------------------------------------------------------
backups_zfs_archive_offsite_dataset: fastpool/backups/raw

# -------------------------------------------------------------------
# DOWNLOADS
# -------------------------------------------------------------------
downloads_dir: "/fastpool/downloads"

# -------------------------------------------------------------------
# NFS
# -------------------------------------------------------------------
nfs_mounts:
  - remote_server: "server-64gb-storage"
    remote_path: "/slowpool/shared/media"
    local_path: "/fastpool/storage-share"
    # mount_options: "defaults,_netdev,x-systemd.after=network-online.target"
