# Asserts that the current platform is supported by the calling role

- name: Assert supported platform
  ansible.builtin.assert:
    that:
      - ansible_facts['system'] | default('unknown') in ansible_assert_platform_supported
    fail_msg: "Role does not support {{ ansible_facts['system'] | default('unknown') }}. Supported platforms: {{ ansible_assert_platform_supported | join(', ') }}"
